 spring.application.name=ywarchitects

spring.datasource.url= jdbc:mysql://localhost:3306/ywarchitects?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=NewPassword123


spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
	
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# 500MB per file, 1GB per request (handles bulk uploads)
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=1GB
server.tomcat.max-swallow-size=1GB


spring.mvc.pathmatch.matching-strategy=ant-path-matcher

# JWT Configuration
jwt.secret= s8axg5EUyDc28v84FbTEA9X4hJU6mjfDmfCq2XHKZsU=
#jwt.access-token.expiration=12000000
# one day
jwt.access-token.expiration=86400000 
jwt.refresh-token.expiration=1209600000
#// 2 weeks

#//haraay s3 bucket
#cloud.aws.region.static=ap-south-1
#cloud.aws.credentials.access-key=AKIA6OI4UP6DOUPI3V5N
#cloud.aws.credentials.secret-key=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
#cloud.aws.s3.bucket=alankarimager

spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS: false
spring.jackson.deserialization.ADJUST_DATES_TO_CONTEXT_TIME_ZONE=false



##//YW ARCHITECTS s3 bucket
aws.enabled=true
cloud.aws.region.static=ap-south-1
cloud.aws.credentials.access-key=AKIA36ETSUHZSZ7Z3G6E
cloud.aws.credentials.secret-key=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
cloud.aws.s3.bucket=ywarchitectsimager



#spring.cache.type=simple
#spring.cache.cache-names=products
#spring.cache.type=simple
#spring.cache.cache-names=products




